apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user_service.fullname" . }}-config
  labels:
    {{- include "user_service.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
