apiVersion: v1
kind: Service
metadata:
  name: {{ include "user_service.fullname" . }}
  labels:
    {{- include "user_service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "user_service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP

